baseURL = "https://forrestywang.github.io/personal-website/"
languageCode = "en-us"
title = "Forrest Wang"
theme = "hugo-coder"
canonifyURLs = true

[markup.highlight]
style = "monokai"

# Content:
[params]
author = "Forrest Wang"
info = ["UW Math Co-op Student", "Aspiring Actuary"]
avatarurl = "/img/avatar.webp"

faviconSVG = "/img/favicon.ico"
favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"
touchIcon = "/img/apple-touch-icon.png"

colorScheme = "auto"

since = 2023

# Social links:
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
url = "https://www.linkedin.com/in/forrestywang/"
target = "_blank"
weight = 1
[[params.social]]
name = "GitHub"
icon = "fa fa-github fa-2x"
url = "https://github.com/forrestywang/"
target = "_blank"
weight = 2
[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
url = "mailto:fy5wang@uwaterloo.ca"
target = "_blank"
weight = 3

# Menu links:
[[menu.main]]
name = "Projects"
url = "posts/"
weight = 1
[[menu.main]]
name = "About"
url  = "/about/"
weight = 2
[[menu.main]]
name = "Resumé"
url = "Resume.pdf/"
type = "application/pdf"
weight = 3
